% ma1_custom_settings_example
% example settings file for use for ma1_process_one_run_pulv_ephys_dataset1
% see defpar in ma1_process_one_run_pulv_ephys_dataset1.m for more options
% should contain variable **settings** as below!

settings = {...
	
	'successful_trials_only',true,...
	'plot_trials',true,...
	'plot_summary',true,...
	
	};
